batch_size: 16
bnorm: true
cluster_output_dim: 64
cluster_size: 4
experiment_id: !!python/object/apply:numpy.core.multiarray.scalar
- !!python/object/apply:numpy.dtype
  args:
  - i4
  - 0
  - 1
  state: !!python/tuple
  - 3
  - <
  - null
  - null
  - null
  - -1
  - -1
  - 0
- !!binary |
  XgAAAA==
gating: false
hid_dim: 16
lrs: 1.0e-05
n_layers: 1
